<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tests')->insert([
            'name'=>'Apolipoprotein A1',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Apolipoprotein B',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Cholesterol',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'CK',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'CKMB',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'CK-MB',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Direct HDL',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Direct LDL',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Homocysteine',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'hsTroponin',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'LDH',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'LDH',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Lp(a)',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Myoglobin',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'NT-proBNP',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Triglycerides',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Troponin I ES',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Wide-Range CRP',
            'amount'=>rand(000,9999),
            'category_id'=>1,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Amylase',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'BUN/Urea',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Calcium',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'CK',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Glucose',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Lactate',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'LDH',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Lipase',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Magnesium',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Phosphorus',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Uric Acid',
            'amount'=>rand(000,9999),
            'category_id'=>2,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Albumin',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'BUN/Urea',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Calcium',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Carbon Dioxide',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Chloride',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Creatinine',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Glucose',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Microalbumin',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'NephroCheck®',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Phosphorus',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Potassium',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Sodium',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Uric Acid',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Urine Protein',
            'amount'=>rand(000,9999),
            'category_id'=>3,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);

        DB::table('tests')->insert([
            'name'=>'Amikacin¶',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Caffeine',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Carbamazepine',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Digoxin',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Gentamicin',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Lithium',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Lidocaine',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Phenobarbital*',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Phenytoin',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Theophylline',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Tobramycin',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Valproic Acid',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Vancomycin',
            'amount'=>rand(000,9999),
            'category_id'=>4,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'AFP',
            'amount'=>rand(000,9999),
            'category_id'=>5,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'CA 15-3TM',
            'amount'=>rand(000,9999),
            'category_id'=>5,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'CA 19-9TM',
            'amount'=>rand(000,9999),
            'category_id'=>5,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'CA 125 IITM',
            'amount'=>rand(000,9999),
            'category_id'=>5,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'CEA',
            'amount'=>rand(000,9999),
            'category_id'=>5,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'IgA',
            'amount'=>rand(000,9999),
            'category_id'=>5,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'IgG',
            'amount'=>rand(000,9999),
            'category_id'=>5,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'IgM',
            'amount'=>rand(000,9999),
            'category_id'=>5,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'PSA',
            'amount'=>rand(000,9999),
            'category_id'=>5,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);



        DB::table('tests')->insert([
            'name'=>'Albumin',
            'amount'=>rand(000,9999),
            'category_id'=>6,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Direct TIBC',
            'amount'=>rand(000,9999),
            'category_id'=>6,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Ferritin',
            'amount'=>rand(000,9999),
            'category_id'=>6,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Folate',
            'amount'=>rand(000,9999),
            'category_id'=>6,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Iron',
            'amount'=>rand(000,9999),
            'category_id'=>6,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Prealbumin',
            'amount'=>rand(000,9999),
            'category_id'=>6,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Total Protein',
            'amount'=>rand(000,9999),
            'category_id'=>6,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Transferrin',
            'amount'=>rand(000,9999),
            'category_id'=>6,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Vitamin B12',
            'amount'=>rand(000,9999),
            'category_id'=>6,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'Alkaline Phosphatase',
            'amount'=>rand(000,9999),
            'category_id'=>7,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Calcium',
            'amount'=>rand(000,9999),
            'category_id'=>7,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Intact PTH',
            'amount'=>rand(000,9999),
            'category_id'=>7,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'NTx',
            'amount'=>rand(000,9999),
            'category_id'=>7,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Phosphorus',
            'amount'=>rand(000,9999),
            'category_id'=>7,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Vitamin D',
            'amount'=>rand(000,9999),
            'category_id'=>7,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);



        DB::table('tests')->insert([
            'name'=>'Anti-HIV 1+2',
            'amount'=>rand(000,9999),
            'category_id'=>8,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'HBsAg',
            'amount'=>rand(000,9999),
            'category_id'=>8,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Rubella IgG',
            'amount'=>rand(000,9999),
            'category_id'=>8,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Total ß-hCG Generation II',
            'amount'=>rand(000,9999),
            'category_id'=>8,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);



        DB::table('tests')->insert([
            'name'=>'Albumin',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Alkaline Phosphatase',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Alpha 1-antitrypsin',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'ALT',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'Ammonia',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'AST',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'BuBc',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Cholinesterase',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'GGT',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'IgA',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'IgG',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'IgM',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Total Bilirubin',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Prealbumin',
            'amount'=>rand(000,9999),
            'category_id'=>9,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);




        DB::table('tests')->insert([
            'name'=>'ASO',
            'amount'=>rand(000,9999),
            'category_id'=>10,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'C3',
            'amount'=>rand(000,9999),
            'category_id'=>10,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'C4',
            'amount'=>rand(000,9999),
            'category_id'=>10,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'CRP',
            'amount'=>rand(000,9999),
            'category_id'=>10,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'IgA',
            'amount'=>rand(000,9999),
            'category_id'=>10,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'IgG',
            'amount'=>rand(000,9999),
            'category_id'=>10,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'IgM',
            'amount'=>rand(000,9999),
            'category_id'=>10,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'RF',
            'amount'=>rand(000,9999),
            'category_id'=>10,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Wide-Range CRP',
            'amount'=>rand(000,9999),
            'category_id'=>10,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'Direct TIBC',
            'amount'=>rand(000,9999),
            'category_id'=>11,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Ferritin',
            'amount'=>rand(000,9999),
            'category_id'=>11,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Folate',
            'amount'=>rand(000,9999),
            'category_id'=>11,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Haptoglobin',
            'amount'=>rand(000,9999),
            'category_id'=>11,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Iron',
            'amount'=>rand(000,9999),
            'category_id'=>11,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'TIBC',
            'amount'=>rand(000,9999),
            'category_id'=>11,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Transferrin',
            'amount'=>rand(000,9999),
            'category_id'=>11,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Vitamin B12',
            'amount'=>rand(000,9999),
            'category_id'=>11,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'Alpha 1-antitrypsin',
            'amount'=>rand(000,9999),
            'category_id'=>12,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Caffeine',
            'amount'=>rand(000,9999),
            'category_id'=>12,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Carbon Dioxide',
            'amount'=>rand(000,9999),
            'category_id'=>12,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Chloride',
            'amount'=>rand(000,9999),
            'category_id'=>12,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Potassium',
            'amount'=>rand(000,9999),
            'category_id'=>12,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Sodium',
            'amount'=>rand(000,9999),
            'category_id'=>12,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'Glucose (csf)',
            'amount'=>rand(000,9999),
            'category_id'=>13,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Total Protein (csf)',
            'amount'=>rand(000,9999),
            'category_id'=>13,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);



        DB::table('tests')->insert([
            'name'=>'Amphetamines',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Barbiturates',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Benzodiazepines',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Buprenorphine/Suboxone',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Amphetamines',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Cocaine Metabolites',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Ecstasy¶',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Ethyl Glucuronide (ETG)#',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Heroin Metabolite (6-AM)',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Hydrocodone',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Methadone',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Methadone Metabolite (EDDP)',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Opiates',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Oxycodone¶',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'PCP',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Propoxyphene',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'THC',
            'amount'=>rand(000,9999),
            'category_id'=>14,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);



        DB::table('tests')->insert([
            'name'=>'Anti-HAV IgM',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Anti-HAV Total ',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Anti-HBc',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Anti-HBc IgM',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Anti-HBe',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Anti-HBs',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Anti-HCV',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Anti-HIV 1+2',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'HBeAg',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'HBsAg',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'HIV Combo',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Rubella IgG',
            'amount'=>rand(000,9999),
            'category_id'=>15,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);



        DB::table('tests')->insert([
            'name'=>'Apolipoprotein A1',
            'amount'=>rand(000,9999),
            'category_id'=>16,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Apolipoprotein B',
            'amount'=>rand(000,9999),
            'category_id'=>16,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Cholestero',
            'amount'=>rand(000,9999),
            'category_id'=>16,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Direct HDL',
            'amount'=>rand(000,9999),
            'category_id'=>16,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Direct LDL',
            'amount'=>rand(000,9999),
            'category_id'=>16,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Triglycerides',
            'amount'=>rand(000,9999),
            'category_id'=>16,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'Amylase',
            'amount'=>rand(000,9999),
            'category_id'=>17,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Lipase',
            'amount'=>rand(000,9999),
            'category_id'=>17,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'Acetaminophen',
            'amount'=>rand(000,9999),
            'category_id'=>18,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Alcohol',
            'amount'=>rand(000,9999),
            'category_id'=>18,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Cholinesterase',
            'amount'=>rand(000,9999),
            'category_id'=>18,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Salicylate',
            'amount'=>rand(000,9999),
            'category_id'=>18,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);



        DB::table('tests')->insert([
            'name'=>'Cortiso',
            'amount'=>rand(000,9999),
            'category_id'=>19,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Free T3',
            'amount'=>rand(000,9999),
            'category_id'=>19,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Free T4',
            'amount'=>rand(000,9999),
            'category_id'=>19,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Lactate',
            'amount'=>rand(000,9999),
            'category_id'=>19,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Cortiso',
            'amount'=>rand(000,9999),
            'category_id'=>19,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'T3 Uptake',
            'amount'=>rand(000,9999),
            'category_id'=>19,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Total T3',
            'amount'=>rand(000,9999),
            'category_id'=>19,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Total T4',
            'amount'=>rand(000,9999),
            'category_id'=>19,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'TSH',
            'amount'=>rand(000,9999),
            'category_id'=>19,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'ß-hydroxybuturate*',
            'amount'=>rand(000,9999),
            'category_id'=>20,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'BUN/Urea',
            'amount'=>rand(000,9999),
            'category_id'=>20,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'C-Peptide',
            'amount'=>rand(000,9999),
            'category_id'=>20,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Creatinine',
            'amount'=>rand(000,9999),
            'category_id'=>20,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Glucose',
            'amount'=>rand(000,9999),
            'category_id'=>20,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Glycated Serum Protein',
            'amount'=>rand(000,9999),
            'category_id'=>20,
            'is_active'=>0,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'HbA1c',
            'amount'=>rand(000,9999),
            'category_id'=>20,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Insulin',
            'amount'=>rand(000,9999),
            'category_id'=>20,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Microalbumin',
            'amount'=>rand(000,9999),
            'category_id'=>20,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);



        DB::table('tests')->insert([
            'name'=>'Estradiol',
            'amount'=>rand(000,9999),
            'category_id'=>21,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'FSH',
            'amount'=>rand(000,9999),
            'category_id'=>21,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'LH',
            'amount'=>rand(000,9999),
            'category_id'=>21,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Progesterone',
            'amount'=>rand(000,9999),
            'category_id'=>21,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Prolactin',
            'amount'=>rand(000,9999),
            'category_id'=>21,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Testosterone',
            'amount'=>rand(000,9999),
            'category_id'=>21,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Total ß-hCG Generation II',
            'amount'=>rand(000,9999),
            'category_id'=>21,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'TSH',
            'amount'=>rand(000,9999),
            'category_id'=>21,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);



        DB::table('tests')->insert([
            'name'=>'Cyclosporine¶',
            'amount'=>rand(000,9999),
            'category_id'=>22,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Everolimus¶',
            'amount'=>rand(000,9999),
            'category_id'=>22,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Mycophenolic Acid¶',
            'amount'=>rand(000,9999),
            'category_id'=>22,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Tacrolimus¶',
            'amount'=>rand(000,9999),
            'category_id'=>22,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);


        DB::table('tests')->insert([
            'name'=>'Amylase',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Calcium',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Chloride',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Creatinine',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Glucose',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Magnesium',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Phosphorus',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Potassium',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Protein',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Sodium',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'BUN/Urea',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
        DB::table('tests')->insert([
            'name'=>'Uric Acid',
            'amount'=>rand(000,9999),
            'category_id'=>23,
            'is_active'=>1,
            'created_at'=>Carbon::now(),
        ],);
    }
}
